# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-05 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.TextField(max_length=1024, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='titulo',
            field=models.CharField(max_length=512, unique=True, verbose_name='Titulo del Evento'),
        ),
    ]
