# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-05 18:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_auto_20200705_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
