# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_auto_20200623_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Departamento',
            field=models.CharField(choices=[('1', 'Distribucion'), ('2', 'Comercial'), ('3', 'Generacion'), ('4', 'Transmision'), ('5', 'Uree'), ('6', 'P y P'), ('7', 'Bienes y Servicios'), ('8', 'ASHO'), ('9', 'Talento Humano'), ('10', 'Procura'), ('11', 'Auditoria Interna'), ('12', 'Desarrolo Social'), ('13', 'Finanzas Lara'), ('14', 'Planificacion Lara'), ('15', 'Desarrollo (Ingenieria)'), ('16', 'Despacho'), ('17', 'ATIT'), ('18', 'Fiscalizacion'), ('19', 'Proyectos mayores'), ('20', 'Comunicaciones Corporativas'), ('21', 'Mesas de Energias'), ('22', 'COD'), ('23', 'Consultoria Juridica'), ('24', 'Tesoreria')], help_text='Coloque el Departamento en donde trabaja', max_length=255),
        ),
    ]
